### ISSUE TITLE
can I help?

### ISSUE THREAD

**Issue by gerbyzation** [okfn/docker-ckan#1]
This looks good, thanks for working on this! I have been doing some work on some ideas for a better docker setup myself, but it's been a bit of a wrestle and this looks better.  

Could you indicate where you could use contributions? I don't know all the ins and outs of CKAN but happy to see if I can help with this.

**Comment by amercader** [comment]
Thanks very much for the offer @gerbyzation. The most pressing thing this needs is testing so if you can give it a go with different scenarios (local dev, production etc) and see if you can find any issues using different features that would be great.

The next thing I want to work is how to make easier to build custom images for your project. Right now you would add any extensions or extra requirements to `ckan/Dockerfile`, but it feels like a better approach would be to have this published in the Docker hub as `ckan:2.7` as a common base that everyone can reuse and then use that on your own `Dockerfile`'s `FROM`. It's more an issue of how to structure and document it really but I'd like to get some thoughts on it.

**Comment by gerbyzation** [comment]
Will do!

I think publishing base images would be a great idea, I was playing with this as well. I think it would be quite useful if a project could be defined by a few files (Dockerfile, compose and .env).
