### ISSUE TITLE
solr looses index after restart

### ISSUE THREAD

**Issue by t-book** [okfn/docker-ckan#108]
Hi,

in my test solr losses the search index after a restart. From what I see this will be solved with following change

https://github.com/okfn/docker-ckan/blob/4b4e21ba4e21ada2e64f35731f56fcd664d16aea/docker-compose.yml#L49

to

`- solr_data:/var/solr/data`

**Comment by s2074135** [comment]
Symptoms are, that after rebooting the containers, datasets are not listed in the dataset view, nor can they be found when using the search box. The datasets can still be listed in the activity stream. t-book's solution solved both of my problems.

**Comment by amercader** [comment]
Should be fixed by #103
