### ISSUE TITLE
Plain install with copied .env.example fail

### ISSUE THREAD

**Issue by terchris** [okfn/docker-ckan#13]
Hi and thanks for the effort in making a simple install

I just renamed the .env.example to .env and then docker-compose build and docker-compose up

All stuff compiles and the containers start. CKAN seems to start on http://localhost:5000/  But displays "Server Error An internal server error occurred" 

Lots of error messages on the log so I do not know which are relevant. 

There is a continuous list of errors like this:
 
db            | ERROR:  relation "system_info" does not exist at character 215
db            | STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.config_update' 
db            | 	 LIMIT 1

And If i click on something on the CKAN web page the log is like this:

db            | ERROR:  relation "system_info" does not exist at character 215
db            | STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.config_update' 
db            | 	 LIMIT 1
db            | ERROR:  relation "group" does not exist at character 65
db            | STATEMENT:  SELECT "group".id AS group_id, "group".name AS group_name 
db            | 	FROM "group" 
db            | 	WHERE "group".state = 'active' AND "group".is_organization = true AND "group".type = 'organization' ORDER BY "group".title ASC
ckan          | Error - <class 'sqlalchemy.exc.ProgrammingError'>: (ProgrammingError) relation "group" does not exist
ckan          | LINE 2: FROM "group" 
ckan          |              ^
ckan          |  'SELECT "group".id AS group_id, "group".name AS group_name \nFROM "group" \nWHERE "group".state = %(state_1)s AND "group".is_organization = true AND "group".type = %(type_1)s ORDER BY "group".title ASC' {'state_1': 'active', 'type_1': 'organization'}
ckan          | URL: http://localhost:5000/organization
ckan          | File '/usr/lib/python2.7/site-packages/weberror/errormiddleware.py', line 171 in __call__
ckan          |   app_iter = self.application(environ, sr_checker)
ckan          | File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
ckan          |   resp = self.call_func(req, *args, **self.kwargs)
ckan          | File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
ckan          |   return self.func(req, *args, **kwargs)
ckan          | File '/usr/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
ckan          |   return request.get_response(self.app)
ckan          | File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
ckan          |   application, catch_exc_info=False)
ckan          | File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
ckan          |   app_iter = application(self.environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
ckan          |   resp = self.call_func(req, *args, **self.kwargs)
ckan          | File '/usr/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
ckan          |   return self.func(req, *args, **kwargs)
ckan          | File '/usr/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
ckan          |   response = request.get_response(self.app)
ckan          | File '/usr/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
ckan          |   application, catch_exc_info=False)
ckan          | File '/usr/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
ckan          |   app_iter = application(self.environ, start_response)
ckan          | File '/srv/app/src/ckan/ckan/config/middleware/pylons_app.py', line 250 in inner
ckan          |   result = application(environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
ckan          |   return self.app(environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
ckan          |   return self.wrap_app(environ, session_start_response)
ckan          | File '/usr/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
ckan          |   response = self.app(environ, start_response)
ckan          | File '/srv/app/src/ckan/ckan/config/middleware/common_middleware.py', line 80 in __call__
ckan          |   return self.app(environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
ckan          |   response = self.dispatch(controller, environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
ckan          |   return controller(environ, start_response)
ckan          | File '/srv/app/src/ckan/ckan/lib/base.py', line 212 in __call__
ckan          |   res = WSGIController.__call__(self, environ, start_response)
ckan          | File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
ckan          |   response = self._dispatch_call()
ckan          | File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
ckan          |   response = self._inspect_call(func)
ckan          | File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
ckan          |   result = self._perform_call(func, args)
ckan          | File '/usr/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
ckan          |   return func(**args)
ckan          | File '/srv/app/src/ckan/ckan/controllers/group.py', line 181 in index
ckan          |   context, data_dict_global_results)
ckan          | File '/srv/app/src/ckan/ckan/logic/__init__.py', line 457 in wrapped
ckan          |   result = _action(context, data_dict, **kw)
ckan          | File '/srv/app/src/ckan/ckan/logic/action/get.py', line 530 in organization_list
ckan          |   return _group_or_org_list(context, data_dict, is_org=True)
ckan          | File '/srv/app/src/ckan/ckan/logic/action/get.py', line 411 in _group_or_org_list
ckan          |   groups = query.all()
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2293 in all
ckan          |   return list(self)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2405 in __iter__
ckan          |   return self._execute_and_instances(context)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2420 in _execute_and_instances
ckan          |   result = conn.execute(querycontext.statement, self._params)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 727 in execute
ckan          |   return meth(self, multiparams, params)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py', line 322 in _execute_on_connection
ckan          |   return connection._execute_clauseelement(self, multiparams, params)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 824 in _execute_clauseelement
ckan          |   compiled_sql, distilled_params
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 954 in _execute_context
ckan          |   context)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1116 in _handle_dbapi_exception
ckan          |   exc_info
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py', line 189 in raise_from_cause
ckan          |   reraise(type(exception), exception, tb=exc_tb)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 947 in _execute_context
ckan          |   context)
ckan          | File '/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py', line 435 in do_execute
ckan          |   cursor.execute(statement, parameters)
ckan          | ProgrammingError: (ProgrammingError) relation "group" does not exist
ckan          | LINE 2: FROM "group" 
ckan          |              ^
ckan          |  'SELECT "group".id AS group_id, "group".name AS group_name \nFROM "group" \nWHERE "group".state = %(state_1)s AND "group".is_organization = true AND "group".type = %(type_1)s ORDER BY "group".title ASC' {'state_1': 'active', 'type_1': 'organization'}
ckan          | 
ckan          | 
ckan          | CGI Variables
ckan          | -------------
ckan          |   CKAN_CURRENT_URL: '/organization'
ckan          |   CKAN_LANG: 'en'
ckan          |   CKAN_LANG_IS_DEFAULT: True
ckan          |   HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
ckan          |   HTTP_ACCEPT_ENCODING: 'gzip, deflate, br'
ckan          |   HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.9,nb-NO;q=0.8,nb;q=0.7'
ckan          |   HTTP_CONNECTION: 'keep-alive'
ckan          |   HTTP_HOST: 'localhost:5000'
ckan          |   HTTP_REFERER: 'http://localhost:5000/'
ckan          |   HTTP_UPGRADE_INSECURE_REQUESTS: '1'
ckan          |   HTTP_USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36'
ckan          |   PATH_INFO: '/organization'
ckan          |   REMOTE_ADDR: '172.19.0.1'
ckan          |   REMOTE_PORT: '8904'
ckan          |   REQUEST_METHOD: 'GET'
ckan          |   REQUEST_URI: '/organization'
ckan          |   SERVER_NAME: 'e5ba25926904'
ckan          |   SERVER_PORT: '5000'
ckan          |   SERVER_PROTOCOL: 'HTTP/1.1'
ckan          |   UWSGI_ROUTER: 'http'
ckan          | 
ckan          | 
ckan          | WSGI Variables
ckan          | --------------
ckan          |   application: <fanstatic.publisher.Delegator object at 0x7fde3fd0fb10>
ckan          |   beaker.cache: <beaker.cache.CacheManager object at 0x7fde3fd0fa50>
ckan          |   beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7fde3fd0f9d0>>
ckan          |   beaker.session: {'_accessed_time': 1519987786.062407, '_creation_time': 1519987786.062407}
ckan          |   ckan.app: 'pylons_app'
ckan          |   fanstatic.needed: <fanstatic.core.NeededResources object at 0x7fde3eca3390>
ckan          |   paste.cookies: (<SimpleCookie: >, '')
ckan          |   paste.registry: <paste.registry.Registry object at 0x7fde4081c5d0>
ckan          |   paste.throw_errors: True
db            | ERROR:  relation "system_info" does not exist at character 215
db            | STATEMENT:  SELECT system_info.id AS system_info_id, system_info.key AS system_info_key, system_info.value AS system_info_value, system_info.state AS system_info_state, system_info.revision_id AS system_info_revision_id 
db            | 	FROM system_info 
db            | 	WHERE system_info.key = 'ckan.config_update' 
db            | 	 LIMIT 1
ckan          |   pylons.action_method: <bound method OrganizationController.index of <ckan.controllers.organization.OrganizationController object at 0x7fde3ecae390>>
ckan          |   pylons.controller: <ckan.controllers.organization.OrganizationController object at 0x7fde3ecae390>
ckan          |   pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
ckan          |   pylons.pylons: <pylons.util.PylonsContext object at 0x7fde3ecae4d0>
ckan          |   pylons.routes_dict: {'action': u'index', 'controller': u'organization'}
ckan          |   repoze.who.api: <repoze.who.api.API object at 0x7fde4140f850>
ckan          |   repoze.who.logger: <logging.Logger object at 0x7fde3fd0fc10>
ckan          |   repoze.who.plugins: {'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7fde3fd2ddd0>, 'friendlyform': <FriendlyFormPlugin 140592530248848>, 'auth_tkt': <CkanAuthTktCookiePlugin 140592530240720>}
ckan          |   routes.route: <routes.route.Route object at 0x7fde3ff86790>
ckan          |   routes.url: <routes.util.URLGenerator object at 0x7fde3ecae050>
ckan          |   uwsgi.core: 1999
ckan          |   uwsgi.node: 'e5ba25926904'
ckan          |   uwsgi.version: '2.0.15'
ckan          |   webob._parsed_query_vars: (GET([]), '')
ckan          |   webob.adhoc_attrs: {'response': <Response at 0x7fde3ecae810 200 OK>, 'language': 'en-us'}
ckan          |   wsgi process: 'Multiprocess'
ckan          |   wsgi.file_wrapper: <built-in function uwsgi_sendfile>
ckan          |   wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7fde3ecae050>, {'action': u'index', 'controller': u'organization'})
ckan          |   x-wsgiorg.fdevent.readable: <built-in function uwsgi_eventfd_read>
ckan          |   x-wsgiorg.fdevent.timeout: None
ckan          |   x-wsgiorg.fdevent.writable: <built-in function uwsgi_eventfd_write>
ckan          | ------------------------------------------------------------

**Comment by terchris** [comment]
Stopped the containers and did a docker-compose up again.
Now it starts. Still lots os log that looks alarming. But it seems to be working. 

I will do more testing.

**Comment by terchris** [comment]
Solved: If you just copy the  .env.example to .env then you must also create a host named ckan in your /etc/hosts file

**Comment by amercader** [comment]
cheers @terchris . I suspect that some of the errors in the logs are caused by some commands trying to be run against the Database or Solr when they are still not ready.

The `ckan` host name is my bad. I added to go around https://github.com/ckan/ckan/issues/4013, because if you use `localhost` then the DataPusher does not work. I should have documented that.
