### ISSUE TITLE
Network configuration

### ISSUE THREAD

**Issue by gerbyzation** [okfn/docker-ckan#17]
Out of the box datapusher and ckan don't work properly due to networking issues.

1. in `.env.example` `CKAN_SITE_URL` is set to `http://ckan:5000`, but from the host machine `ckan` won't resolve. 
2. Datapusher raises the error that processing is sucessful, but unable to post to result_url. With the default settings this would be to an endpoint on `ckan:5000`, of which it can't resolve the host. 

The easy remedy for the first point is to set `CKAN_SITE_URL` to `http://localhost:5000` (#16), but this probably won't play with a solution for point 2.

Datapusher needs to be able to post a request to CKAN, so it needs to be able to resolve whatever the host is set to in `CKAN_SITE_URL` to something that points to either the host machine localhost (where the port is bound to the CKAN docker container) or to the container straight away. 

At the moment I solved this by adding a hosts entry in the datapusher container, mapping `ckan` to the ip `docker.for.mac.localhost` resolves to, and an entry on my host machine mapping `ckan` to `localhost`. Adding a link in docker-compose doesn't work as it creates a circular dependency and would require for development to either change the service name or the host name. 

Ideally there would be a fixed IP that would always resolve to the host machine, regardless if it's resolved at the host or in a container/VM, but I am unaware of such a thing.

Alternatively it would be great to work out a recommended approach to configure this so it's easy to get datapusher working locally.

**Comment by amercader** [comment]
For anyone being hit by this if you use the latest images with the latest patch release (which you should) just add `CKAN__DATAPUSHER__CALLBACK_URL_BASE=http://ckan:5000` to your `.env` file and hopefully it should work fine (as shown in 4b5f5f61cf83c293f90fd7822799d2e1fb75dcbd)

**Comment by linforestzhang** [comment]
> 
> 
> For anyone being hit by this if you use the latest images with the latest patch release (which you should) just add `CKAN__DATAPUSHER__CALLBACK_URL_BASE=http://ckan:5000` to your `.env` file and hopefully it should work fine (as shown in [4b5f5f6](https://github.com/okfn/docker-ckan/commit/4b5f5f61cf83c293f90fd7822799d2e1fb75dcbd))

Not working for my CKAN v2.9.1 in Docker.
