### ISSUE TITLE
check out similar work to dockerize ckan in data4dappl

### ISSUE THREAD

**Issue by OriHoch** [okfn/docker-ckan#19]
Hey, this repo is very similar to the work I did [here](https://github.com/OriHoch/data4dappl), check out the [docker-compose](https://github.com/OriHoch/data4dappl/blob/master/docker-compose.yml)

My setup is used successfully in production at https://www.odata.org.il/

Worth to have a look if you can learn something from that, I'll have a look if I can use your work

One thing which might be useful for you is the kubernetes setup under [k8s directory](https://github.com/OriHoch/data4dappl/tree/master/k8s)

**Comment by amercader** [comment]
Thanks a lot @OriHoch, I'll definitely have a look when I get the chance. Regarding kubernetes there is an active effort to have a standard(-ish) k8s ckan deployment in here: https://github.com/ckan/ideas-and-roadmap/issues/206

You might want to add to the discussion there!
