### ISSUE TITLE
build fails without ckan/patches directory

### ISSUE THREAD

**Issue by jtorreggiani** [okfn/docker-ckan#24]
Hello! I just cloned the repository for the first time. Following the setup instructions, running `docker-compose build` failed on step 3/4 with the following error.

```
Step 3/4 : COPY patches ${APP_DIR}/patches
ERROR: Service 'ckan' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder230327039/patches: no such file or directory
```

Easy enough to fix by just adding an empty `ckan/patches` directory. It would be useful to either include an empty directory with a `.gitkeep` file or clarify in the `README` that a `patches` directory is required to build the project.

**Comment by amercader** [comment]
Good catch @jtorreggiani, what you suggest with the git file sounds good

**Comment by niryariv** [comment]
Encountered the same problem, the PR above fixed it. Might be a good idea to merge :)
