### ISSUE TITLE
Create a simple a new page 

### ISSUE THREAD

**Issue by israeldesigner** [okfn/docker-ckan#60]
Hi I'm new in Ckan, and I need to create a new page, where the page it's gonna be  127.0.0.1:5000/apipage, I've copied the template folder apipage as about page, but when I put on the web this page shows 404, I need help, so its a static page for the  project

**Comment by amercader** [comment]
Please use the main [CKAN repo discussions](https://github.com/ckan/ckan/discussions) for support requests like this
