### ISSUE TITLE
Installing cryptography fails as it requires rust tools

### ISSUE THREAD

**Issue by Zharktas** [okfn/docker-ckan#66]
When ckan extension has PyOpenSSL as an requirement, the installation fails as compiling cryptography [requires rust tools now](https://github.com/pyca/cryptography/issues/5771).  This happens for example in ckanext-harvest where latest master doesn't pass CI [anymore](https://github.com/ckan/ckanext-harvest/runs/1987688547).

Should rust tools be installed in the image or should the extension depending on cryptography install them themselves?

Apparently fixed already in #65, but the images in docker hub haven't been updated.

**Comment by amercader** [comment]
Thanks @Zharktas I could have sworn I pushed them but obviously didn't. Let me check

**Comment by amercader** [comment]
Images are up to date, but #65 was only applied to the datapusher image so it probably needs to be added to the 2.9 image as well. Will try to do it soon, also PRs welcome

**Comment by Zharktas** [comment]
Ah didn't notice that only datapusher image was updated with new dependencies, I'll submit a PR soon for this.

**Comment by amercader** [comment]
I added this change in 72b8fcc.
Test pass again: https://github.com/ckan/ckanext-harvest/actions/runs/602860133
