### ISSUE TITLE
Automate Docker Builds when pushing

### ISSUE THREAD

**Issue by amercader** [okfn/docker-ckan#77]
When we push to the repo an action should kick in that builds the Docker image and pushes it to the Docker Hub registry.

These actions looks like what we need: https://github.com/marketplace/actions/build-and-push-docker-images

Building on every single commit seems a bit wasteful as not all changes affect the actual images or all images across all versions but it's a good starting point.

What's important is to build the right images, with the right Dockerfiles and right Docker tags (`2.7`, `2.8`, `2.9` and `2.9-py2` both on `ckan-base` and `ckan-dev`)

**Comment by avdata99** [comment]
Closing this @amercader.
